from __future__ import annotations

"""V5 production cleanup: delete only proven pre-epoch anonymous latency exhaust.

The target table is certification-only accounting. Current production reads it only
for rows at/after the exact release's persistent certification epoch. V5 therefore
removes only rows strictly older than that boundary, in small indexed batches, while
leaving the table/index and certification-replication triggers intact.

All other V4 protections remain unchanged. In particular, event lineage, paper
checkpoint/accounting, wallet intelligence, strategy state, risk-refresh history,
synthetic provenance and unknown tables remain protected. Replication-journal pruning
still requires an externally proven certifier watermark and is independent from this
cleanup; delete deltas generated by this target are deliberately retained for the
certifier.
"""

import json
import os
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any

from . import certification_epoch
from . import production_data_cleanup_v4 as prior

CLEANUP_VERSION = "production-data-cleanup-v5-pre-epoch-anonymous-latency"
ENABLED_ENV = prior.ENABLED_ENV
RUN_ID_ENV = prior.RUN_ID_ENV
ROLE_ENV = prior.ROLE_ENV
ACK_WATERMARK_ENV = prior.ACK_WATERMARK_ENV
TELEMETRY_HOURS_ENV = prior.TELEMETRY_HOURS_ENV
CleanupBlocked = prior.CleanupBlocked
BATCH_SIZE = 500
TARGET_TABLE = "anonymous_candidate_latency_failures"
TARGET_COLUMNS = ("id", "failed_at", "reason", "outcome", "count", "max_age_ms")
EPOCH_TABLE = "certification_release_epochs"
EPOCH_COLUMNS = ("release_commit", "started_at")

base = prior.base
cleanup_stale_certification_exports = prior.cleanup_stale_certification_exports


def _release_epoch(
    db: sqlite3.Connection,
    schema: dict[str, base.TableShape],
) -> dict[str, str]:
    if EPOCH_TABLE not in schema:
        raise CleanupBlocked("release certification epoch table is unavailable")
    base._required_columns(schema, EPOCH_TABLE, EPOCH_COLUMNS)
    release = certification_epoch.release_commit_from_env()
    if not release:
        raise CleanupBlocked("exact release commit unavailable for certification-epoch cleanup")
    row = db.execute(
        "SELECT started_at FROM certification_release_epochs WHERE release_commit=?",
        (release,),
    ).fetchone()
    if row is None:
        raise CleanupBlocked("current exact release has no durable certification epoch")
    started_at = str(row[0])
    try:
        parsed = datetime.fromisoformat(started_at)
    except ValueError as exc:
        raise CleanupBlocked("current release certification epoch is not valid ISO-8601") from exc
    if parsed.tzinfo is None:
        raise CleanupBlocked("current release certification epoch is timezone-naive")
    return {"release_commit": release, "started_at": started_at}


def _target_failed_at_index(db: sqlite3.Connection) -> str:
    for row in db.execute(f"PRAGMA index_list({base._quote_identifier(TARGET_TABLE)})").fetchall():
        name = str(row[1])
        columns = [
            str(info[2])
            for info in db.execute(
                f"PRAGMA index_info({base._quote_identifier(name)})"
            ).fetchall()
        ]
        if columns and columns[0] == "failed_at":
            return name
    raise CleanupBlocked("anonymous latency table lacks an indexed failed_at retention boundary")


def _target_replication_triggers(db: sqlite3.Connection) -> list[str]:
    rows = db.execute(
        "SELECT name,sql FROM sqlite_master WHERE type='trigger' AND tbl_name=? ORDER BY name",
        (TARGET_TABLE,),
    ).fetchall()
    if len(rows) != 3:
        raise CleanupBlocked(
            f"anonymous latency cleanup requires exactly three replication triggers; found {len(rows)}"
        )
    operations: set[str] = set()
    names: list[str] = []
    for row in rows:
        name = str(row[0])
        sql = str(row[1] or "")
        upper = sql.upper()
        if "CERTIFICATION_REPLICATION_CHANGES" not in upper:
            raise CleanupBlocked(f"unexpected non-replication trigger on anonymous latency table: {name}")
        if "AFTER DELETE" in upper:
            operations.add("delete")
        elif "AFTER INSERT" in upper:
            operations.add("insert")
        elif "AFTER UPDATE" in upper:
            operations.add("update")
        else:
            raise CleanupBlocked(f"unrecognized replication trigger on anonymous latency table: {name}")
        names.append(name)
    if operations != {"delete", "insert", "update"}:
        raise CleanupBlocked(f"anonymous latency replication trigger set is incomplete: {sorted(operations)}")
    return names


def _sequence_value(db: sqlite3.Connection, table: str) -> int:
    row = db.execute("SELECT seq FROM sqlite_sequence WHERE name=?", (table,)).fetchone()
    return int(row[0]) if row is not None else 0


def _delete_pre_epoch_latency_exhaust(
    db: sqlite3.Connection,
    schema: dict[str, base.TableShape],
    *,
    batch_size: int = BATCH_SIZE,
) -> dict[str, Any]:
    if TARGET_TABLE not in schema:
        return {"status": "table_absent", "deleted": 0}
    base._required_columns(schema, TARGET_TABLE, TARGET_COLUMNS)
    if schema[TARGET_TABLE].primary_key != ("id",):
        raise CleanupBlocked("anonymous latency table primary key no longer matches proven contract")
    if schema[TARGET_TABLE].foreign_keys:
        raise CleanupBlocked("anonymous latency table unexpectedly gained outbound foreign keys")
    inbound = base._inbound_foreign_keys(schema, TARGET_TABLE)
    if inbound:
        raise CleanupBlocked(f"anonymous latency table has inbound foreign keys: {inbound}")
    index_name = _target_failed_at_index(db)
    triggers = _target_replication_triggers(db)
    epoch = _release_epoch(db, schema)
    if batch_size <= 0:
        raise CleanupBlocked("anonymous latency deletion batch size must be positive")

    target_sequence_before = _sequence_value(db, TARGET_TABLE)
    replication_sequence_before = _sequence_value(db, prior.REPLICATION_TABLE)
    newest_stale = db.execute(
        f"SELECT id,failed_at FROM {base._quote_identifier(TARGET_TABLE)} "
        "WHERE failed_at<? ORDER BY failed_at DESC,id DESC LIMIT 1",
        (epoch["started_at"],),
    ).fetchone()
    if newest_stale is None:
        return {
            "status": "no_pre_epoch_rows",
            "deleted": 0,
            "certification_epoch": epoch,
            "failed_at_index": index_name,
            "replication_triggers": triggers,
            "target_sequence_before": target_sequence_before,
            "target_sequence_after": target_sequence_before,
            "replication_sequence_before": replication_sequence_before,
            "replication_sequence_after": replication_sequence_before,
            "replication_delete_deltas_generated": 0,
        }

    quoted = base._quote_identifier(TARGET_TABLE)
    total = 0
    while True:
        cursor = db.execute(
            f"DELETE FROM {quoted} WHERE id IN ("
            f"SELECT id FROM {quoted} WHERE failed_at<? ORDER BY failed_at,id LIMIT ?)",
            (epoch["started_at"], int(batch_size)),
        )
        deleted = int(cursor.rowcount if cursor.rowcount >= 0 else 0)
        db.commit()
        total += deleted
        if deleted < batch_size:
            break

    stale = db.execute(
        f"SELECT id,failed_at FROM {quoted} WHERE failed_at<? ORDER BY failed_at DESC,id DESC LIMIT 1",
        (epoch["started_at"],),
    ).fetchone()
    if stale is not None:
        raise CleanupBlocked("pre-epoch anonymous latency rows remain after bounded deletion")

    target_sequence_after = _sequence_value(db, TARGET_TABLE)
    if target_sequence_after != target_sequence_before:
        raise CleanupBlocked("anonymous latency AUTOINCREMENT sequence changed during deletion")
    replication_sequence_after = _sequence_value(db, prior.REPLICATION_TABLE)
    generated = replication_sequence_after - replication_sequence_before
    if generated != total:
        raise CleanupBlocked(
            "anonymous latency deletion did not produce exactly one durable replication delta per row: "
            f"deleted={total} generated={generated}"
        )

    first_remaining = db.execute(
        f"SELECT id,failed_at FROM {quoted} ORDER BY failed_at,id LIMIT 1"
    ).fetchone()
    last_remaining = db.execute(
        f"SELECT id,failed_at FROM {quoted} ORDER BY failed_at DESC,id DESC LIMIT 1"
    ).fetchone()
    return {
        "status": "deleted_pre_release_certification_epoch",
        "deleted": total,
        "certification_epoch": epoch,
        "newest_deleted_before": [int(newest_stale[0]), str(newest_stale[1])],
        "failed_at_index": index_name,
        "replication_triggers": triggers,
        "bounded_batch_size": int(batch_size),
        "target_sequence_before": target_sequence_before,
        "target_sequence_after": target_sequence_after,
        "replication_sequence_before": replication_sequence_before,
        "replication_sequence_after": replication_sequence_after,
        "replication_delete_deltas_generated": generated,
        "remaining_rows": "not_scanned",
        "remaining_oldest": (
            [int(first_remaining[0]), str(first_remaining[1])] if first_remaining is not None else None
        ),
        "remaining_newest": (
            [int(last_remaining[0]), str(last_remaining[1])] if last_remaining is not None else None
        ),
    }


def _protected_plan(schema: dict[str, base.TableShape], *, role: str) -> dict[str, str]:
    plan = prior._protected_plan(schema, role=role)
    if role == "authoritative" and TARGET_TABLE in plan:
        plan[TARGET_TABLE] = "predicate-controlled:strictly-before-current-release-certification-epoch"
    return plan


def execute_cleanup(
    database_path: Path,
    *,
    role: str,
    run_id: str,
    acknowledged_watermark: int | None = None,
    telemetry_hours: float = 24.0,
) -> dict[str, Any]:
    if role.strip().lower() == "certifier":
        return prior.execute_cleanup(
            database_path,
            role=role,
            run_id=run_id,
            acknowledged_watermark=acknowledged_watermark,
            telemetry_hours=telemetry_hours,
        )

    del telemetry_hours
    role = role.strip().lower()
    if role != "authoritative":
        raise CleanupBlocked("cleanup role must be authoritative or certifier")
    run_id = base._validate_run_id(run_id)
    database_path = Path(database_path).resolve()
    if not database_path.exists() or not database_path.is_file() or database_path.is_symlink():
        raise CleanupBlocked(f"database path is not a regular file: {database_path}")

    marker_dir = database_path.parent / ".production-cleanup"
    report_path = marker_dir / f"{run_id}.json"
    if report_path.exists():
        previous = json.loads(report_path.read_text(encoding="utf-8"))
        if previous.get("status") == "success":
            return {**previous, "idempotent_replay": True}
        raise CleanupBlocked(f"cleanup run id already has non-success durable state: {run_id}")

    report: dict[str, Any] = {
        "version": CLEANUP_VERSION,
        "run_id": run_id,
        "role": role,
        "database_path": str(database_path),
        "status": "running",
        "started_at": base._utcnow(),
        "paper_only": True,
        "live_money_authority": False,
        "signing_available": False,
        "transaction_submission_available": False,
        "history_bounded_preflight": True,
    }
    base._atomic_json(report_path, report)

    db = base._connect(database_path)
    try:
        db.execute("BEGIN IMMEDIATE")
        db.commit()
        schema = prior._extract_schema_bounded(db)
        before = prior._measure_bounded(database_path, db, schema)
        plan = _protected_plan(schema, role=role)
        protected_before = prior._protection_snapshot(db, schema, plan)
        epoch = _release_epoch(db, schema)

        report["preflight"] = {
            "writer_exclusion": "begin_immediate_acquired",
            "full_integrity_scan": "deferred_until_post_compaction",
            "history_scaled_counts": False,
            "event_ledger_full_scan": False,
            "unknown_tables_default_protected": True,
            "current_release_certification_epoch": epoch,
        }
        report["protected_set"] = plan
        report["protection_before"] = protected_before
        report["before"] = before
        report["unproven_categories"] = prior._unproven_categories(schema)
        base._atomic_json(report_path, report)

        # Prune only already-acknowledged journal history. If no certifier watermark is
        # supplied this is a no-op; target deletes below create NEW deltas that remain.
        replication = prior._delete_acknowledged_replication(
            db,
            schema,
            acknowledged_watermark=acknowledged_watermark,
        )
        latency = _delete_pre_epoch_latency_exhaust(db, schema)

        report["deleted_rows"] = {
            "certification_replication_changes": replication,
            TARGET_TABLE: latency,
            "synthetic_candidate_history": 0,
            "risk_refresh_measurements": 0,
        }
        report["deleted_rows_total"] = prior._deleted_total(report["deleted_rows"])
        report["externally_proven_certifier_acknowledged_watermark"] = acknowledged_watermark
        report["orphan_files"] = cleanup_stale_certification_exports(database_path)
        base._atomic_json(report_path, report)

        compaction = base._compact(database_path, db)
        schema_after = prior._extract_schema_bounded(db)
        after = prior._measure_bounded(database_path, db, schema_after)
        final_integrity = prior._final_integrity(db)
        after["integrity"] = final_integrity
        if not final_integrity["ok"]:
            raise CleanupBlocked("post-cleanup SQLite integrity/foreign-key check failed")
        plan_after = _protected_plan(schema_after, role=role)
        if plan_after != plan:
            raise CleanupBlocked("table protection plan changed during cleanup")
        protected_after = prior._protection_snapshot(db, schema_after, plan_after)
        prior._assert_protection_unchanged(protected_before, protected_after)
        remaining_stale = db.execute(
            f"SELECT id FROM {base._quote_identifier(TARGET_TABLE)} WHERE failed_at<? LIMIT 1",
            (epoch["started_at"],),
        ).fetchone()
        if remaining_stale is not None:
            raise CleanupBlocked("pre-epoch anonymous latency exhaust reappeared during cleanup")

        report["compaction"] = compaction
        report["after"] = after
        report["protection_after"] = protected_after
        report["reclaimed"] = {
            "database_bytes": int(before["files"]["database_bytes"]) - int(after["files"]["database_bytes"]),
            "wal_bytes": int(before["files"]["wal_bytes"]) - int(after["files"]["wal_bytes"]),
            "filesystem_free_bytes": int(after["files"]["filesystem_free_bytes"]) - int(before["files"]["filesystem_free_bytes"]),
            "freelist_pages": int(before["pragma"]["freelist_count"]) - int(after["pragma"]["freelist_count"]),
        }
        report["status"] = "success"
        report["completed_at"] = base._utcnow()
        base._atomic_json(report_path, report)
        return report
    except Exception as exc:
        try:
            db.rollback()
        except Exception:
            pass
        report["status"] = "blocked"
        report["completed_at"] = base._utcnow()
        report["error"] = f"{type(exc).__name__}:{exc}"
        base._atomic_json(report_path, report)
        raise
    finally:
        db.close()


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Fail-closed one-shot production SQLite cleanup v5")
    parser.add_argument("--database", default=os.getenv("SOLANA_ROI_DATABASE_PATH") or os.getenv("SOLANA_ROI_DB_PATH"))
    parser.add_argument("--role", default=os.getenv(ROLE_ENV, ""))
    parser.add_argument("--run-id", default=os.getenv(RUN_ID_ENV, ""))
    parser.add_argument(
        "--ack-watermark",
        type=int,
        default=(int(os.environ[ACK_WATERMARK_ENV]) if os.getenv(ACK_WATERMARK_ENV) else None),
    )
    args = parser.parse_args(argv)
    if not base._env_true(ENABLED_ENV):
        print(json.dumps({"version": CLEANUP_VERSION, "status": "disabled", "enabled": False}, sort_keys=True))
        return 0
    if not args.database:
        raise CleanupBlocked("cleanup enabled but database path is not configured")
    result = execute_cleanup(
        Path(args.database),
        role=args.role,
        run_id=args.run_id,
        acknowledged_watermark=args.ack_watermark,
    )
    print("ROI_PRODUCTION_DATA_CLEANUP " + json.dumps(result, sort_keys=True, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "BATCH_SIZE",
    "CLEANUP_VERSION",
    "CleanupBlocked",
    "TARGET_TABLE",
    "_delete_pre_epoch_latency_exhaust",
    "_release_epoch",
    "execute_cleanup",
    "main",
]
